### ISSUE TITLE
Add Finch support

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#1]

**Comment by ripleymj** [comment]
Still need HIDAPI

**Comment by ripleymj** [comment]
Closed by 3a5eb6816638d308cf9b96aa00e2b99d56b019ac

**Comment by ripleymj** [comment]
Re-opening this, per @Zamua. Finch support may have never worked, and duplicating it into Ansible was insufficient.

**Comment by kylelaker** [comment]
`export PYTHONPATH=$PYTHONPATH:/path/you/want/to/add` [Ref](https://askubuntu.com/a/471168)

**Comment by kylelaker** [comment]
Are there any more changes in particular that need to made for Spring or should this issue be re-targeted to Fall 2018? Or do we want to wait for comments on beta 1?

**Comment by ripleymj** [comment]
I'm ok retargeting this to fall. That doesn't preclude pushing fixes sooner, but I don't think there's the demand for this in the spring to be worth blocking the image release.

**Comment by kylelaker** [comment]
Do we need to look at the steps at the bottom of https://www.finchrobot.com/learning/compiling-python-programs

**Comment by kylelaker** [comment]
Looks like we already have libusb1.0.0. We probably want to avoid the script. It symlinks `libudev.so.1` to to `libudev.so.0`. The udev rules in the zip have an extra line compared to the .rules file we have.

**Comment by kylelaker** [comment]
Re-targeting to Fall 2019. I am not convinced it would be useful to push this change so late in the semester (I believe the Finch projects have already begun and/or ended) and CS 101 will not be offered in Spring.

**Comment by kylelaker** [comment]
According to current students and TAs for CS 101, this has not been an issue this semester for students running the virtual machine. Closing.
