### ISSUE TITLE
Update to Eclipse Oxygen 2

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#102]

**Comment by kylelaker** [comment]
http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/2/eclipse-java-oxygen-2-linux-gtk-x86_64.tar.gz

`02ea91d64704e205c5c01f024ec6a9f033e0fdd1  eclipse-java-oxygen-2-linux-gtk.tar.gz`
