### ISSUE TITLE
Create OEM playbook for pre-distribution tasks

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#11]

**Comment by ripleymj** [comment]
Base appliance size is 2.25 GB

Ansible and git packages missing by default.

**Comment by ripleymj** [comment]
Package diff: https://gist.github.com/ripleymj/c46c3cb945c3b7e47a52f8f4baea29e3

**Comment by ripleymj** [comment]
`apt-get remove libreoffice-* thunderbird* hexchat* pidgin* transmission-* gimp* pix* rhythmbox* tomboy bluez* simple-scan xplayer* vlc* openvpn btrfs-tools mono-* xscreensaver-* fonts-noto-cjk mint-backgrounds-sarah mint-backgrounds-serena libllvm3.8` saves about 1GB

**Comment by ripleymj** [comment]
`apt-get remove fonts-beng* fonts-deva* fonts-gargi* fonts-gujr* fonts-guru* fonts*guru* fonts*gujr* fonts-gubbi fonts-kacst* fonts-khmeros-core fonts-kalapi fonts-lohit-* fonts-lao fonts-nakula fonts-nanum fonts-lklug-sinhala fonts-navilu fonts-pagul fonts-sahadeva fonts-orya-extra fonts-samyak-* fonts-sarai fonts-tlwg-* fonts-wqy-microhei fonts-sil-* fonts-smc fonts-takao-pgothic fonts-telu-extra fonts-tibetan-machine myspell-en-au myspell-en-gb myspell-en-za myspell-es myspell-it myspell-pt* wbritish hyphen-de hyphen-fr hyphen-it hyphen-ru hunspell-de-at hunspell-de-ch hunspell-de-de hunspell-en-ca hunspell-en-gb hunspell-en-za hunspell-fr hunspell-fr-classical hunspell-it hunspell-ru`

**Comment by ripleymj** [comment]
- `apt-get autoremove`
- `apt-get clean`
- `dpkg --get-selections | grep deinstall | awk '{print $1}' | xargs dpkg --purge
- `dd if=/dev/zero of=bigfile bs=1M; sync; rm bigfile`

**Comment by kylelaker** [comment]
The following could be a start for .desktop files. A notable problem is that the terminal closes immediately after ansible-pull exits with no way to tell whether it succeeded.
```
[Destop Entry]
Type=Application
Version=1.1
Name=COURSE
Comment=Configure packages and settings for COURSE
TryExec=ansible-pull
Exec=ansible-pull -U https://github.com/jmunixusers/cs-vm-build -i hosts -K -t COURSE
Icon=xterm-color
Categories=System;ConsoleOnly
Terminal=true
```

**Comment by ripleymj** [comment]
So we could wrap ansible-pull in a very minimal .sh and pass the tags as $1, or try "ansible-pull; read" to make the window pause at the end.

**Comment by kylelaker** [comment]
True. It's possible the Exec line could even be:
`Exec=/bin/sh -c "ansible-pull -U https://github.com/jmunixusers/cs-vm-build -i hosts -K -t COURSE; read"`. Then it wouldn't be necessary to have a .sh file.

If it is easier, we could use a shell script, which might make it easier to provide context to the user about how to move forward in the cases where Ansible fails (like the have a version that's too new/old), and we  could do something like this:

```bash
#!/usr/bin/env bash
# bash is used because read -p is undefined in POSIX sh

if ansible-pull -U https://github.com/jmunixusers/cs-vm-build -i hosts -K -t "$1"; then
    exit_status=0
else
    echo ""
    echo -e "\e[1mERROR\e[0m"
    echo "There were errors running the playbook. Please try to run this again. If you"
    echo "continue to experience issues, please report a bug at:"
    echo "  https://github.com/jmunixusers/cs-vm-build/issues/new"
    exit_status=1
fi
read -p "Press ENTER to exit" junk
exit $exit_status
```
