### ISSUE TITLE
JGrasp 2.0.4_03 no longer available

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#112]
The latest version of JGrasp is 2.0.4_04 and the old version is no longer available for download. This breaks CS149. `roles/jgrasp/vars/main.yml` should be updated with the updated download URL.

**Comment by ripleymj** [comment]
Some day we should see if we can POST to their download form: http://spider.eng.auburn.edu/user-cgi/grasp/grasp.pl and chase the redirect it serves to the latest version

**Comment by kylelaker** [comment]
Can we make that a separate issue targeted to FA18?

**Comment by ripleymj** [comment]
Yes, just thinking out loud there.

**Comment by kylelaker** [comment]
I definitely like the idea! I just wanted to close this with the PR but not forget about that.

**Comment by ripleymj** [comment]
Never mind, that breaks our hash scheme.
