### ISSUE TITLE
Eclipse Oxygen.3

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#121]
Should be a new Eclipse release today: https://wiki.eclipse.org/Simultaneous_Release

**Comment by kylelaker** [comment]
These need to be double-checked (which I can do tomorrow), but the hash and download URL appear to be the following for Linux 64-bit.

2b7605ab5806dfe2738ec978f39c1a1d0c7be547

http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3/eclipse-java-oxygen-3-linux-gtk-x86_64.tar.gz&mirror_id=1249
