### ISSUE TITLE
Add y86 reference solution

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#128]
The following binaries should be added to the cs261 tag:

* `yref`
* `ysim`
* `yis`
* `yas`

The above binaries are available on the CS `stu` server.

The manpage written by @Advill should also be added, though we may want to expand on it to specify the mutually-exclusive flags in the synopsis section.

I think the preference for this would be to create a `y86` role and to put everything in there. This would require:

* `ansible-galaxy init y86` in roles/
* Putting the binaries in roles/y86/files
* Addings tasks to create `/opt/bin`, `/opt/share/man/man1/`
* Adding tasks in y86/tasks/main.yml to move the files to the proper locations in /opt/
* Adding the above man directory to MANPATH in /opt/csvmprofile
* Adding the above bin directory to PATH in /opt/csvmprofile

Work on this issue should be coordinated with @lam2mo. Please communicate with him before submitting a pull request to ensure binaries are stripped as appropriate (especially `yref`).

**Comment by lam2mo** [comment]
Just a comment here: I do plan to revise the project slightly for the Fall 2018 semester, which will involve some minor changes to the yref executable. I am hoping to make these changes during the summer but I'm not sure exactly when.

**Comment by kylelaker** [comment]
After some discussion out-of-band, the plan forward seems to be to implement this with the existing executables and then drop in the new ones as necessary. If this doesn't get finished before the update executables are available, then we will just use those.

**Comment by lam2mo** [comment]
I think I have finished the revisions to the 261 project. Binaries are located on `stu` in the standard location. The list of binaries is slightly modified and shortened:

* `y86ref` - this is the project reference solution
* `ysim` - this is the reference simulator from the textbook
* `yas` - this is the assembler from the textbook

The manpage will need to be updated accordingly, I presume.

**Comment by kylelaker** [comment]
I plan on working on this issue soon. I just want to confirm that the binaries in `/cs/students/cs261/y86` are stripped and there aren't any further changes expected.

**Comment by lam2mo** [comment]
Yes, they are up-to-date and the reference interpreter (y86ref) is stripped. There is still a small chance that I will get motivated and add a new A-level requirement to P2 (in which case there will be new behavior for y86ref) but for now I'm thinking that's unlikely.
