### ISSUE TITLE
Make the wrapper script remember roles

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#135]
Each time the wrapper runs, ideally, the roles selected the last time the script was run will be selected automatically (but still be able to be unchecked). This probably will require a change in config format, possibly to JSON or YAML (and since so much of the project is YAML, it may be ideal).

I would like to see something like either of the following as a sample config.

```
---
git_url: "https://github.com/jmunixusers/cs-vm-build"
git_branch: sylvia
previous_roles:
  - common
  - cs101
```

or

```
{
"git_url": "https://github.com/jmunixusers/cs-vm-build",
"git_branch": "sylvia",
"previous_roles": [ "common", "cs101" ]
}
```

**Comment by ripleymj** [comment]
I'd prefer the format choice be guided more by what Python supports easily, reliably, and without external dependencies. We also want to make sure not to give the impression that unchecking a preselected option will uninstall that role.

**Comment by kylelaker** [comment]
Good point. I thought PyYAML was built-in, but I guess it isn't. JSON support should be. And we can adjust the wording at the top to say, "Select the courses to add/update the configuration for" or something to that effect

**Comment by kylelaker** [comment]
Initial work on this exists in my remember-roles branch. I don't want to submit a PR until #132 is merged.
