### ISSUE TITLE
Eclipse upgrade - June 27, 2018

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#136]
http://www.eclipse.org/eclipse/news/4.8/

**Comment by kylelaker** [comment]
Will this just be for future releases or will we update the `sylvia` branch for this as well?

**Comment by ripleymj** [comment]
Without thinking about it too much, I'd say we leave `sylvia` at 4.7.x with Java 8.

**Comment by kylelaker** [comment]
I like that idea. I'll add this to the Fall 2018 milestone and not tag it with `sylvia`.
