### ISSUE TITLE
Verify "real" user detection

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#143]
`cups-pk-helper` in 19 seems to be detected as a real user. Our current logic looks for `/sbin/nologin`, but it seems 19 has changed to `/usr/sbin/nologin`. This user has UID 113, which is less than the 1000 we look for, so I'm not sure what's happening here.

**Comment by kylelaker** [comment]
The section in question begins at: https://github.com/jmunixusers/cs-vm-build/blob/master/roles/common/tasks/main.yml#L44

I almost wonder if user id (`item.value.1`) is a `str`. If it is, we'll probably just need to change ln 47 to ` - int(item.value.1) >= 1000`, but we'll need to test that actually works. I'm not sure how much python is allowed in jinja2 conditionals.

```
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> '113' >= 1000
True
```

**Comment by kylelaker** [comment]
Seems like the jinja way to do this will be to do `{{ item.value.1 | int }}` on lines 42 and 47.
