### ISSUE TITLE
Figure out appropriate JVM version

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#158]
Perhaps related to #154 

We're installing both default-jdk and openjdk-8. Default now depends on the openjdk-11 package, which identifies as Java 10.0.1. We probably should only have one JVM version installed.

**Comment by kylelaker** [comment]
I don't see a great harm in having both installed; I feel like if we pick one `default-jdk` might be better. jGRASP seems to work well enough; I haven't seen any DrJava issues; Eclipse Photo should be fine on 10 and 11. We might be able to choose a default using the [Alternatives module](https://docs.ansible.com/ansible/2.5/modules/alternatives_module.html).

Hopefully we'll see a final release of jGRASP 2.0.5 which has Java 10-11 support before we ship this fall, but if we don't, maybe we can just set the alternative to Java 8.

**Comment by ripleymj** [comment]
jGRASP 2.0.5 is RTM now. When skipping openjdk-8-jdk installation, DrJava fails to launch with this error: https://sourceforge.net/p/drjava/support-requests/344/

openjdk-8 removal patch is available on my remove-jdk8 branch, but I'm skipping the PR for now until I understand this DrJava failure.

**Comment by kylelaker** [comment]
Since the last commit to DrJava was in 2014, we probably shouldn't hold our breath on that being fixed. We'll probably just need to ship openjdk-8-jdk and openjdk-11-jdk in the fall.

We should use this as a reason to get in touch with our CS 149 professors to see if they even use DrJava anymore or if they're all recommending jGRASP so we can take care of this for Spring 2019.

Assuming this works for you, we can either close this or retarget it to Spring 2019.

**Comment by ripleymj** [comment]
I'm going to retarget this for Spring 2019. Keeping JDK8/DrJava at the moment is the least risky option for getting this image shipped.

**Comment by kylelaker** [comment]
Based on some discussions with professors, it sounds like DrJava is slowly being phased out in favor of jGRASP. We'll see what happens in the spring and fall, but my understanding is that for the most part, the department has transitioned to using Java 10 and therefore using Java 10-compatible IDEs.

Maybe in that week after Thanksgiving, we can start surveying our professors on which IDE they plan to use for CS 149.
