### ISSUE TITLE
Investigate Mint codec problems

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#175]
Per @ChrisMayfield,

> When I run "Install Multimedia Codes" from the menu, I get an error message that it failed and to fix broken packages first. So I ran "apt install mint-meta-codecs" from the terminal and got:
`The following packages have unmet dependencies:
 mint-meta-codecs : Depends: adobe-flashplugin but it is not installable
                    Depends: libavcodec-extra`

If we get this working, we can consider a backport, but I don't believe this should block Fall 2018 at this point.

**Comment by ChrisMayfield** [comment]
Wow, they're prompting users to install (insecure) flash over HTTP? Is the package signed, at least?

**Comment by kylelaker** [comment]
Yes, I believe that Debian, Ubuntu, and Mint all have fairly strict packaging standards that include requiring GPG signatures. My understanding is that this includes the Release file and individual packages.

The default for `apt` across all distros is to use HTTP. It's surprising that `archive` doesn't at least provide the option, though.
