### ISSUE TITLE
Improve documentation and/or flexibility of the OEM role

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#189]
The OEM role is currently only really fit to be run on Linux Mint that is intended to be run in a virtual machine. There are many issues that come up if the OEM role is run on actual hardware (such as removing bluez libraries and failing because USB drivers are installed). These are necessary in the VM.

We should either:

 - have `oem-vm` and `oem-hw` roles that are intended for VMs or physical hardware respectively
 - document that OEM should only be run if the device is a virtual appliance and how to best bootstrap getting the `common` role on the machine initially.

**Comment by ripleymj** [comment]
Just browsing the ansible setup variables, the following seem to be the best indicators of our VM:
        "ansible_bios_version": "VirtualBox", 
        "ansible_product_name": "VirtualBox", 
        "ansible_system_vendor": "innotek GmbH", 
        "ansible_virtualization_type": "virtualbox", 
        "ansible_virtualization_role": "guest",

**Comment by kylelaker** [comment]
Oh wow. I really like `ansible_virtualization_role`. I'd like to see if that gets set consistently across VirtualBox, VM Ware, Parallels, and maybe a few others.

**Comment by ripleymj** [comment]
## Bash script
| Task                | VM          | HW          |
| ------------------- | ----------- | ----------- |
| assert_mint         | Should      | Should      |
| apt update          | Must        | Must        |
| Install ansible/git | Must        | Must        |
| Run OEM playbook    | Must        | Must        |
| Zero empty space    | Must        | Should not  |

## OEM Playbook
| Task                | VM          | HW          |
| ------------------- | ----------- | ----------- |
| assert Mint         | Should      | Should      |
| apt update          | Must        | Must        |
| Remove unused       | Should      | Maybe not   |
| Remove unused deps  | Should      | Should      |
| Upgrade all         | Must        | Must        |
| Install deps        | Must        | Must        |
| Clean apt           | Must        | Maybe not   |
| Skel desktop        | Must        | Must        |
| Log directory       | Must        | Must        |
| Desktop README      | Must        | Must        |
| Hide mint welcome   | Should      | Should      |
| Create local share apps | Must    | Must        |
| Banish USB 2/3      | Must        | Must not    |

## Task shortcut Playbook
| Task                | VM          | HW          |
| ------------------- | ----------- | ----------- |
| VMTools dir         | Must        | Must        |
| Polkit wrapper      | Must        | Must        |
| Ansible GUI         | Must        | Must        |
| Tux icon            | Must        | Must        |
| Ansible desktop icon| Must        | Must        |

**Comment by ripleymj** [comment]
Also, it looks like Ansible tries to borrow from `virt-what`, and can detect more platforms than I'd expect: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/virtual/linux.py
