### ISSUE TITLE
Cannot scroll previous output in GUI

### ISSUE THREAD

**Issue by ChrisMayfield** [jmunixusers/cs-vm-build#190]
It would be nice if you could scroll back the output in the "JMU CS VM Configuration" tool, especially if there are errors or warnings. Right now there's no scroll bar, and wheel / two-finger scrolling doesn't work.

**Comment by kylelaker** [comment]
Yeah, we currently have that disabled because it's what comes with calling `set_sensitive(False)` on the VTE widget. I've been wanting to find a good way to disallow input to that widget while still allowing scrolling. Thanks for opening an issue so I remember to do it!

**Comment by kylelaker** [comment]
The above PR will fix this. It allows the user to scroll through the output but also disallows entering text. It does some other fixes to scrolling like always going to the bottom of output as there is more output and allowing infinite scroll back.

At the moment, my plan is for this to be included in the spring and not patch the current release; however, if needed we can update the current semester's release with the fix. Do you have a preference on this?

**Comment by ChrisMayfield** [comment]
Thanks! Next spring is fine; it's not critical for this fall.
