### ISSUE TITLE
Eclipse download timeout

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#191]
Several people reported Eclipse bundle fetch timed out. Let's see if we can make this better.

**Comment by kylelaker** [comment]
Having looked through the logs from at least one occurrence of this, it seems like we don't have much to go on.

```
2018-09-05 19:53:14,595 p=21089 u=root |  TASK [eclipse : Fetch Eclipse bundle] ******************************************
2018-09-05 19:54:04,489 p=21089 u=root |  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: timeout: timed out
2018-09-05 19:54:04,491 p=21089 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to create temporary content file: timed out"} 
```

**Comment by cfrome77** [comment]
I was going to submit an issue when I had this issue. I had tried 3 times, getting the above error each time. I wanted to try one more time before submitting an issue, and behold on the fourth try it worked. Not sure why it took 4 tries before working. I did read something about maybe increasing the timeout with `timeout:` under `get_url:`

**Comment by ripleymj** [comment]
That was kind of my feeling, and I think `retries` is another option. It looks like the default is 10 seconds, so I'm considering 30 seconds, 3 retries for now, and if we find a better way we can easily replace those.

**Comment by Advill** [comment]
Working on this, will test these changes before making the PR.

**Comment by kylelaker** [comment]
@Advill: I feel like @ripleymj and I looked into `retries` and it didn't do what we thought it did, so it may be good to double-check that. Unfortunately, we did not document that discussion.

**Comment by ripleymj** [comment]
Hmm, I do remember discussing some aspect of this, but also have no idea what conclusion we came to. It looks like timeouts are part of `get_url` but retries are part of the Ansible core. I want to say what we discovered was that it seemed like the Eclipse download service had just died when we saw this, and no reasonable amount of retries would solve it. Part of the conversation was on adding a well-known (vt.edu?) designated fallback mirror after trying the Eclipse service, but I don't remember if that was the end of the conversation.

**Comment by Advill** [comment]
In my current branch `eclipse-timeout` I set both a longer `timeout` and 3 `retries`, you have a good point that the eclipse download service might just die, so I'll add a fallback. It seems futile to try multiple times if the download fails after 30 seconds, should I keep the `retries` or simply fallback after the first failure?
