### ISSUE TITLE
Gazebo7 Package Error

### ISSUE THREAD

**Issue by cfrome77** [jmunixusers/cs-vm-build#192]
The following error occurs for the `gazebo7` package:
```
2018-09-06 21:16:01,846 p=24242 u=root |  failed: [localhost] (item=[u'ros-kinetic-desktop-full', u'gazebo7', u'rviz', u'g++']) => {"changed": false, "item": ["ros-kinetic-desktop-full", "gazebo7", "rviz", "g++"], "msg": "No package matching 'gazebo7' is available"}
```

I also get this message when running `sudo apt-get install gazebo7` about there being a newer version with a package called `gazebo9`: 
```
Package gazebo7 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gazebo9:i386 gazebo9

E: Package 'gazebo7' has no installation candidate
```

**Comment by kylelaker** [comment]
Thanks, Chris! We haven't done much testing of the CS 354 role this semester, so it's great you caught this. We looked at the CS lab machines the other day and it seems like they switched to ROS' Melodic release. I'm wondering if us doing the same this would help resolve this issue.

Maybe related to #85
