### ISSUE TITLE
Timeshift potentially fills hard disk 100%

### ISSUE THREAD

**Issue by ChrisMayfield** [jmunixusers/cs-vm-build#200]
The new Timeshift feature that ships with Mint 19 aggressively uses disk space. It's not turned on by default, but the Update Manager "warns" (nags) users to set up snapshots. After some time (several weeks?) the /timeshift/snapshots directory takes about 10 GB. If the disk usage reaches 100%, the VM only boots to tty1. Deleting the contents of /timeshift/snapshots immediately fixes the problem. I've reported this issue upstream: https://bugs.launchpad.net/linuxmint/+bug/1738065

As a workaround (to prevent this issue in future semesters), you might want to add an Ansible task that unchecks "Show a warning if the system snapshots are not set up" in the Update Manager. Or maybe it would be better to remove Timeshift altogether. There might be a way to configure /etc/timeshift.json to avoid this issue.

**Comment by ripleymj** [comment]
Just some initial triage:
- `timeshift` can be removed without removing a larger meta-package
- `mintupdate` uses the dconf setting /com/linuxmint/updates/warn-about-timeshift to control the warning
- Purging the `timeshift` package does not remove existing backups
- /etc/default/timeshift.json gets copied to /etc/timeshift.json on first use, leaving us an OEM option
- Ansible has a dconf module to modify preferences like this

**Comment by ripleymj** [comment]
@showalrm can you read this over, so we can talk about it on Wednesday?

**Comment by ripleymj** [comment]
After some discussion yesterday, I'd like to recommend we try the following to aim the footgun at the less useful toes:

- Remove `timeshift` package in OEM
- Set `warn-about-timeshift` to false in both OEM and Common. I don't think backup warnings are an expected feature of an update utility, and this won't preclude someone manually configuring backups.

If we later decide to add more functionality around VM-hardware detection, I'd be open to considering relaxing that Common task on real iron. If Timeshift becomes a more stable application, we may also be able to modify `/etc/default/timeshift.json` to max out at something like 50% disk space. At this point, we have no prior art for modifying JSON via Ansible, so I'd like to stick with the two listed items to get something in place soon.

**Comment by kylelaker** [comment]
In addition to the launchpad bug that @ChrisMayfield linked to, the timeshift issue is being tracked in teejee2008/timeshift#332.

**Comment by ripleymj** [comment]
I've ok'd @showalrm putting the dconf tasks in task-shortcuts, in anticipation of #201.

**Comment by kylelaker** [comment]
Most of the work on this can be seen in #204 which is already referenced above. I want to acknowledge the huge amount of work that @showalrm put into this --- it definitely ended up being a bit more of an interesting fix than we expected.

The basic changes that were made were:

 - Removing the `timeshift` packages *only* in the OEM role
 - Changing the user settings (for all users) for mintupdate so it doesn't warn when Timeshift is disabled
 - The above change requires starting the `mintupdate-launcher` in the system tray

Thanks, @ChrisMayfield for reporting it and to @showalrm for fixing it.

It's also been backported in #205, so students can re-run the configuration utility and it will apply this fix (without the `timeshift` removal). I would highly recommend that all students re-run to get these changes.

This will not help students who have already enabled Timeshift. Unfortunately, just disabling Timeshift could affect users who have enabled it intentionally. This fix will be bundled into the Spring image.

**Comment by jcartner-young** [comment]
Is there any progress on Timeshift filling up disks and not detecting free space correctly?

What TS thinks:
![Screenshot_2021-02-20_21-11-41](https://user-images.githubusercontent.com/40523205/108608654-4c8a9e00-73c0-11eb-9659-a25ab452bab2.png)

Reality:
![Screenshot_2021-02-20_21-11-26](https://user-images.githubusercontent.com/40523205/108608658-52807f00-73c0-11eb-80c3-e3a67787f4ef.png)

**Comment by ripleymj** [comment]
@jcartner-young we don't deal with Timeshift any more, after this issue was closed two years ago. This repo is for a building a very targeted VM, not for any work on Timeshift itself. It looks like you've joined the conversation in the upstream repo - hopefully they're able to help you there.

**Comment by jcartner-young** [comment]
Mike,
I really appreciate the feedback - Thank you for the info.
Fingers crossed, but breath not held ;)

James
On Sat, Feb 20, 2021 at 21:21, Mike Ripley  wrote:
 @jcartner-young (https://github.com/jcartner-young) we don't deal with Timeshift any more, after this issue was closed two years ago. This repo is for a building a very targeted VM, not for any work on Timeshift itself. It looks like you've joined the conversation in the upstream repo - hopefully they're able to help you there.
