### ISSUE TITLE
Consider using Python 2

### ISSUE THREAD

**Issue by showalrm** [jmunixusers/cs-vm-build#202]
The CS101 textbook uses Python 2 rather than Python 3. To avoid conflicts with our curriculum, we should install Python 2.

**Comment by showalrm** [comment]
@coledn

**Comment by ripleymj** [comment]
Can we open a bug against the textbook instead? :)

Python 2 is dead on Jan 1, 2020, and via things like #174, we'd been asked to start moving to Python 3. Are the assignments using Python 2isms that don't run under 3, or does it just suggest that you launch Python 2 instead?

**Comment by ripleymj** [comment]
Looks like Pearson is phasing out the 2015 12th Edition, with a 13E in 2019. Hopefully they've cleaned this up in there. @mayfiecs, have you seen into the mysterious future here?

**Comment by ChrisMayfield** [comment]
I have a desk copy of the 13th Edition, and indeed they are using Python 3 now. Thank you for following up and for closing the issue.
