### ISSUE TITLE
Add support for 361

### ISSUE THREAD

**Issue by Advill** [jmunixusers/cs-vm-build#206]
Some 361 required C libraries are not included in the image. I don't have the specific libraries yet, will be testing later this week. Will mark down here what is missing specifically.

**Comment by Advill** [comment]
I believe that this can be fixed simply by running the `adv-prog-pkgs` role, I've implemented this [here in my fork](https://github.com/advill/cs-vm-build), but am holding the pull request as I have not tested it yet, nor added it to the GUI.

**Comment by ripleymj** [comment]
I'm a little confused by what git's trying to tell me. Do you want to rename `adv-prog-pkgs` or create a new subset role? If you do that, do we trigger `c-programming-essentials` for both 261 and 361, and then just `c-programming-essentials` for 361? If you're creating a new role, use `ansible-galaxy init` to get the skeleton framework.

We've got a couple other projects going on to reorganize `common` and `task-shortcuts`, as well as cleaning up the looping syntax throughout the project. I'd just like to understand where you're headed to avoid sadness of people tripping over each other.

You may also want to start down a branch rather than hacking directly in `master`.

**Comment by Advill** [comment]
At first I thought i needed to add a new role, but after checking I realized all packages should be installed by `adv-prog-pkgs`, so I've simply added a new tag to that roll in the `local.yml` file. This shouldn't step on anyone, at least yet, as this is the only change I've made as of yet, and hopefully the only change I need to make.

**Comment by ripleymj** [comment]
Ahh, gotcha! Yep, start with `local.yml` and then `task-shortcuts/files/uug_ansible_wrapper.py` if you're feeling adventurous.

**Comment by kylelaker** [comment]
So, if 361 is just going to install the same things as CS 261 (minus `y86`), I'd almost rather we just change the wrapper to say, `CS 261/361`. If we can find some meaningful difference in the package requirements, I am okay with splitting them off into separate tags.

**Comment by Advill** [comment]
That's true. There shouldn't be anything missing after the install of `build-dependencies` and `g++` right? I'll pull the VM and take a look to be sure, but considering there's nothing extreme I'll close this.

**Comment by ripleymj** [comment]
I'm ok with changing the label in the wrapper to indicate support for CS 361. Feel free to leave this issue open to track that.

**Comment by kylelaker** [comment]
Actually, I take back my suggestion to just modify the script. We've put in a lot of effort to ensure that when a user selects a class, it is offered to them each time they run the script. I am concerned that if a student selects the "CS 261/361" role and we later split those into two separate roles that we will offer that user 261 again and again when they really want 361.

Perhaps we should add a 361 tag. This way we prevent this potential issue in the future.

Sorry, @Advill for sending you on so many direction with this. Let's see if @ripleymj has any suggestions for this and then you and I can try to work on this after our meeting tomorrow night.

**Comment by Advill** [comment]
Woops, finished the first set of instructions earlier today, just didn't have time to submit the PR. If we are not doing it like this I'd be happy to do some more work on it, but I'll just leave it as a PR for now.
