### ISSUE TITLE
Desktop templates should use path variables

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#21]
- [x] ./roles/jgrasp/templates/jgrasp.desktop.j2
- [x] ./roles/drjava/templates/drjava.desktop.j2
- [x] ./roles/drjava/templates/drjava.sh.j2
- [x] ./roles/aptana/templates/aptana.desktop.j2
- [x] ./roles/eclipse/templates/eclipse.desktop.j2

**Comment by kylelaker** [comment]
Aptana was already using the path variable
