### ISSUE TITLE
CS354 USB warning is oddly distorted

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#212]
The CS354 USB 2/3 warning box appears with very odd dimensions, which would be nice to fix if we're pursuing CS354 support.

![virtualbox_jmu linux mint fa18_22_10_2018_15_57_26](https://user-images.githubusercontent.com/12940106/47473240-e4235600-d7df-11e8-9489-ca07dd2c858c.png)

**Comment by kylelaker** [comment]
This window is displayed using `zenity` (not the wrapper script). We should look into command line arguments to `zenity` that would allow us to specify dimensions.
