### ISSUE TITLE
Investigate moving mirror changes from user to common

### ISSUE THREAD

**Issue by showalrm** [jmunixusers/cs-vm-build#227]
The oem role does not currently use the JMU mirrors, and changing it might benefit the oem build process.

**Comment by kylelaker** [comment]
That's a great idea! We might want to consider seeing if it could be moved to `common`. I don't think it would be a problem for it to be there. I think @ripleymj might be doing some work on shipping the JMU CS mirror by default in #224 but it would be nice to get it into the Ansible roles.

Feel free to self-assign this and work on it if you'd like!
