### ISSUE TITLE
Printers always report as changed

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#23]
Every time the playbook is run, it always reports two changes: the printers. Could [HP41/ansible-cups](/HP41/ansible-cups/) help?

**Comment by ripleymj** [comment]
ansible-cups appears to wrap the lpadmin/lpstat commands under the hood, and I'm not sure how I feel about importing modules at this point. Something like this crudely silences the change notice:
```
- name: Add printers
  shell: >
    lpstat -p "{{ item.name }}" ||
    lpadmin -p "{{ item.name }}" -E
    -v "{{ item.queue }}"
    -L "{{ item.descr }}"
    -m "drv:///sample.drv/generic.ppd"
    -o "Duplex=DuplexNoTumble"
    -o "Option1=True"
    -o "printer-is-shared=false"
  register: lpstat_result
  changed_when: '"Invalid destination name" in lpstat_result.stderr'
  with_items: "{{ printers }}"
```
