### ISSUE TITLE
Upgrade base to Linux Mint 19.1 Tessa

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#241]
The new version of Mint has [officially](https://blog.linuxmint.com/?p=3669) been released. I have confirmed its presence on mirror.cs [here](http://mirror.cs.jmu.edu/pub/linuxmint/images/stable/19.1/).

**Comment by ripleymj** [comment]
Do you want to bump the semester to Sp19 in Packer and the VM skeleton scripts as well?
