### ISSUE TITLE
packer: No audio in exported VMs

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#249]
When creating an appliance using Packer, audio does not work in the resulting VM. The audio settings are disabled in VirtualBox and it doesn't seem we have any existing commands to enable them. We should try to get this working before shipping the VM in the spring if we can.

**Comment by ripleymj** [comment]
Odd, I thought I had that working with the `--audioout on`. I'll have to take another look at that.

**Comment by kylelaker** [comment]
I guess I should clarify this happened creating and running the VM on VirtualBox 6.0. If we see that it works on 5.2.x, then I'll just have to downgrade, but it would still be good to look into.

**Comment by kylelaker** [comment]
This is almost certainly just a 6.0.0 issue which we're not going to be using this spring. Targetting this to the fall and we can figure it out as the 6.0.x series stabilizes.

**Comment by kylelaker** [comment]
We have now seen this on 5.2.24
