### ISSUE TITLE
Menu shortcuts do not appear

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#25]
On first installation, menu shortcut didn't populate, but appeared after reboot. Consider adding a `update-desktop-database` handler to anything that creates desktop shortcuts.

**Comment by kylelaker** [comment]
Even if it might be a little overkill, I feel like the `update-desktop-database` handler should run if any file in `/usr/local/share/applications/` is created or modified (or if the directory is created or modified), and the user should be nudged to reboot.

**Comment by ripleymj** [comment]
Multiple handlers do not seem well-supported in Ansible < 2.2, where handlers can subscribe to a message topic. For now, we could:
- Just trigger the `Suggest restart` handler
- Just `update-desktop-database` and hope for the best
- Put `update-desktop-database` handler ahead of `Suggest restart` and have it chain trigger
- `Suggest restart` when the directory is created, and `update-desktop-database` when a .desktop file is changed

**Comment by kylelaker** [comment]
It looks like #95 resolved this at least for the VM we ship. I'm not sure how much effort we want to expend on making this work in all possible scenarios (such as when the machine wasn't first configured with the OEM role). This can certainly remain targeted to the fall, but I do want to make sure there's a comment that this is resolved for our primary target

**Comment by kylelaker** [comment]
@ripleymj -- Is this still a problem? If so, let's add it to the list for next UUG meeting

**Comment by ripleymj** [comment]
I think #95 fixed this well enough.
