### ISSUE TITLE
VirtualBox Extension Pack Link Incorrect in CS354 USB Warning

### ISSUE THREAD

**Issue by cfrome77** [jmunixusers/cs-vm-build#254]
The CS354 warning link on [line 22](https://github.com/jmunixusers/cs-vm-build/blob/master/roles/robot-pkgs/vars/main.yml#L22) to the page about installing the VirtualBox Extensions pack is missing `/VM` and throws a 404 when clicked. I will go ahead and submit a pull request with the fix.
@kylelaker Let me know if this needs to be backported.

**Comment by kylelaker** [comment]
Let's go ahead and back port this to `tessa`, but not `tara`. Thanks!

**Comment by kylelaker** [comment]
For some reason this did not get auto-closed. Closing thanks to #255 and #256
