### ISSUE TITLE
Add 430 Install script

### ISSUE THREAD

**Issue by Advill** [jmunixusers/cs-vm-build#257]
As 430 requires a few specific programming languages, I feel it reasonable to add it's own install file.

The things that I know would be required right now are
* Ruby
* RVM (?)
* GHC
* GProlog

As well as the general text editing and similar programs installed alongside 361.

**Comment by ripleymj** [comment]
Feel free to submit a draft PR if you want early feedback :)

**Comment by Advill** [comment]
Haven't finished yet but I should have something done by the end of the weekend.

**Comment by lam2mo** [comment]
I’m hoping we don’t need RVM honestly. IIRC @Advill ran into a non-Mint-specific issue that was resolved using RVM but I forget whether we determined it was necessary on Mint.

**Comment by ripleymj** [comment]
Ok, I was going to be very surprised if 430 was using bleeding edge Ruby features.

**Comment by kylelaker** [comment]
So Debian includes 2.3.3 ([source](https://packages.debian.org/stretch/ruby)) and Ubuntu and derivatives will have 2.5.1 ([source](https://packages.ubuntu.com/bionic/ruby)). Ruby 2.6.0 was *just* released not long ago ([source](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/)). I am okay with shipping 2.5.x for now. If they were shipping super old versions, I would lean more towards using `rvm`; however, on Ubuntu and Mint (which is what we plan to target with this tool), I think we're okay.

If you see an older version of Ruby getting installed, we can try to figure things out.

**Comment by kylelaker** [comment]
Hopefully that addresses concerns about Ruby versions?

**Comment by lam2mo** [comment]
Yes, it does for me. MacOS still ships with 2.3.7 by default so I'm actually fine with any of those. If students really want to be able to use features from the most recent version they can install it themselves. It's also possible that Dr. Simmons will choose to restrict them to using an older version anyway. I think as recently as last year we were telling folks not to use any functionality added after 2.0 (and linked them to the older documentation as a precaution).

**Comment by ripleymj** [comment]
Probably the wrong place to leave this note to future self, but it seems relevant. If we know we have a bunch of people planning to use the VM this summer, let's try to get an updated build posted close to then so they don't have to patch so much on first boot.

**Comment by lam2mo** [comment]
FWIW, "a bunch" here = ~12.

**Comment by ripleymj** [comment]
What I hear you saying is THE LARGEST SUMMER INSTALLFEST IN UUG HISTORY!

**Comment by lam2mo** [comment]
The version of GNU Prolog shipped with Ubuntu/Mint is currently broken. Any 430 deployment for the UUG VM will probably need to use the .deb that the CS admins made today, or build it from scratch. The .deb is available on stu (contact me for path).

**Comment by lam2mo** [comment]
We are very seriously considering switching to SWI-Prolog for next year. It seems to be more robust and have a more active user and developer community (e.g., the last SWI-Prolog update was last month compared to a year ago for GNU Prolog).

Ubuntu has a version of SWI-Prolog in its repository, but apparently it is sometimes out of date. The SWI-Prolog developers maintain a PPA with their own package:

http://www.swi-prolog.org/build/PPA.txt

**Comment by Advill** [comment]
I'll just go ahead and write my PR under the assumption that we are going to switch to SWI-prolog, as the installation for gprolog would be easy enough to switch back to.

**Comment by Advill** [comment]
closed with #261
