### ISSUE TITLE
Create welcome/what's next doc on desktop

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#27]
- [x] Write documentation
- [x] Write .desktop file
- [ ] Create OEM task for .desktop file

**Comment by ripleymj** [comment]
We already have two installation docs:
- https://w3.cs.jmu.edu/cs101/virtual/index.html
- https://jmunixusers.github.io/presentations/InstallFest.html
but perhaps we need something to explain how to get started inside the VM

**Comment by kylelaker** [comment]
So my understanding is that all those steps are essentially going to remain the same with the exception that once the user has booted into their desktop, they will need to double-click an entry on their desktop for each class that they're in?

**Comment by ripleymj** [comment]
We probably need to review how the image will be used. The existing documentation is good for something like 101, where students are encouraged to download the image in advance, and then work through importing and booting it for the first time with light guidance. For 101, that may be as far as the course takes them, and then they run the playbook(s) on their own. For UUG InstallFests, we may take them through running a playbook.

I think having a "Start Here" doc on the desktop, so they have some idea how to continue when they are on their own, though it would be good to mention this at the end of the existing docs. Possible topics include:
- How to run Ansible playbooks
- How to get additional packages from Mint
- Powering down/snapshotting the VM
- Generating ssh keys
- Reporting problems and contributing to the cs-vm-build project
- Attending UUG meetings

**Comment by ripleymj** [comment]
This should probably be hosted in the jmunixusers/presentations repository.

**Comment by kylelaker** [comment]
Please see jmunixusers/presentations#15 for the Welcome doc

**Comment by kylelaker** [comment]
Keeping this here for safe keeping.

```
[Desktop Entry]
Name=VM README
Type=Link
URL=https://jmunixusers.github.io/welcome-to-vm.html
Icon=test-html
```
