### ISSUE TITLE
Error with cs430: programming-languages in local.yaml

### ISSUE THREAD

**Issue by cfrome77** [jmunixusers/cs-vm-build#271]
the line in `local.yaml` that specifies the programming languages role throws the error in the picture below. I believe this is due to the `local.yaml` file refering to the cs430 role name as `programming-languages` when the folder for the role is named `programming-langs`.

![capture](https://user-images.githubusercontent.com/16628337/53372003-c138b800-391f-11e9-8ff8-f3eac55b68e0.PNG)

**Comment by kylelaker** [comment]
Thanks for reporting this! Working on it now!

**Comment by kylelaker** [comment]
Do you mind testing the branch in the above PR just to be sure that everything runs (you don't need to install the 430 content if you don't want to)?
