### ISSUE TITLE
Update wrapper desktop icon to new flat Tux

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#281]
We should probably update the desktop icon in the common role files.

[jmu-tux.zip](https://github.com/jmunixusers/cs-vm-build/files/3075615/jmu-tux.zip)

**Comment by kylelaker** [comment]
FWIW the About dialog in the script also needs to be updated

**Comment by ripleymj** [comment]
Looks like they share the same file.
