### ISSUE TITLE
Consider alternative approaches to apt update failure

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#292]
After #290 and #291 taught us that Ansible will consider failure of any mirror as fatal, we made the step optional. Adding both the CS mirror and the Ubuntu upstream was intentional, to increase odds of success, but with this failure early in the playbook, software installation cannot succeed.

Opening this issue for discussion on alternate approaches that would allow apt source failover.

**Comment by kylelaker** [comment]
Do we remember what the issue was that prevented access to the mirrors? Was the most likely cause resolved as part of #316? Or was the upstream mirror inaccessible?

Do we have any ideas on how to proceed after #298?

**Comment by ripleymj** [comment]
mirror.cs wasn't accessible to visitor wireless, which is resolved now. I'm out of ideas for how to fix this, but still think it's better to let Ansible proceed even if a mirror is down.

**Comment by kylelaker** [comment]
Ahh that's right. I definitely agree that we should continue to work towards resolving this, just trying to remember the context for it.

**Comment by kylelaker** [comment]
Is this still a goal for Spring 2020? Is there any indication Mint 19.3 gave any additional ways to handle this?

**Comment by ripleymj** [comment]
Nothing that I know of. I'll probably leave it open until we ship, then just kill it instead of bumping it forward another semester

**Comment by ripleymj** [comment]
Only thing I ever found was converting the `sources.list` to `deb mirror+file:`, but the Mint utilities don't know how to parse this and try to overwrite it.
