### ISSUE TITLE
dpkg fails on dbus upgrade

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#293]
Occasionally, on a fresh install, the auto-updater and Ansible will run at the same time and trip over each other. Perhaps there's a way to avoid this.

**Comment by kylelaker** [comment]
Can we do this with a delay and retries? That's not really avoidance but rather just working around the issue. Not sure what other options may exist

**Comment by ripleymj** [comment]
Tracking upstream: https://github.com/linuxmint/mintupdate/issues/552
https://forums.linuxmint.com/viewtopic.php?t=296589

**Comment by ripleymj** [comment]
This has been abandoned upstream, so I don't see much chance of making progress.

**Comment by kylelaker** [comment]
Ugh I mean as long as we don't expect many more Tessa installs before we release Tina, I guess accepting the upstream decision is probably best.

If we expect any installs, we should release some documentation.
