### ISSUE TITLE
ROS Melodic install error

### ISSUE THREAD

**Issue by cfrome77** [jmunixusers/cs-vm-build#302]
The following error occurred on my latest attempt to update with cs345 checked (image-sp19e):
`019-07-22 17:21:04,540 p=16549 u=root |  TASK [robot-pkgs : Install robot development packages] 2019-07-22 17:21:05,361 p=16549 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'ros-melodic-desktop-full' is available"}`

This is strange because the package reference does exist in the Packages file ([http://mirror.umd.edu/packages.ros.org/ros/ubuntu/dists/bionic/main/binary-amd64/Packages](http://mirror.umd.edu/packages.ros.org/ros/ubuntu/dists/bionic/main/binary-amd64/Packages)) on the mirror

**Comment by kylelaker** [comment]
Interesting. This reminds me of an old issue we had where it seemed like the first `apt update` didn't really work. I don't think we ever really found a good solution to that.

Can you run `apt update` on the command line then re-run the 354 role?

**Comment by cfrome77** [comment]
when I ran `sudo apt update` as you suggested I received the following error related to the two repositories we use for ROS, saying that the public key is not valid.

`W: GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://mirror.umd.edu/packages.ros.org/ros/ubuntu bionic Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://mirror.umd.edu/packages.ros.org/ros/ubuntu bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

after deleting the apt-key and adding the new one as per this post: [https://answers.ros.org/question/325039/apt-update-fails-cannot-install-pkgs-key-not-working/](https://answers.ros.org/question/325039/apt-update-fails-cannot-install-pkgs-key-not-working/) 
I no longer received the above error. I then re-ran the cs354 role and it finished without any issues.

There is another thread about the GPG key being changed: [https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454)

**This can be marked closed**
