### ISSUE TITLE
Investigate replacing shell with command, or remove completely

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#308]
Follow-on from #297 lint cleanup, see if command can replace shell, or if we remove this handler completely.

https://github.com/jmunixusers/cs-vm-build/blob/a8acb6d927b37b133835248a60ef8eb374deb160/roles/user/handlers/main.yml#L18

**Comment by ripleymj** [comment]
This handler fails when run on Ubuntu 19.04. As we were already considering reworking or removing this, I'm more inclined to remove it at this point.

**Comment by kylelaker** [comment]
I agree with the argument to remove it. We're performing an update as soon just before or after this disappears from the task bar and it will re-appear the next time the VM is updated. Otherwise we're stuck littering `when: {{ ansible_distribution }} == ...` in various places.
