### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by Brennaser** [jmunixusers/cs-vm-build#321]
This error keeps appearing after I select what I want to configure and run the program. Any ideas?

![THE Config error](https://user-images.githubusercontent.com/54820278/64133422-ed883200-cda3-11e9-8a44-78835854f045.png)

**Comment by ripleymj** [comment]
Can you scroll the other window back and see what the failed task is? I suspect it's something related to "Upgrade installed software".

If it's that, open up File -> Settings, and change the branch from "tina" to "master", and then try reinstalling your courses. Please let me know what you see, we may need to push an update to the rest of the class.

**Comment by Brennaser** [comment]
You were right, so I did as you said and now its kind of just stuck. I left it alone for a few hours and its still just here.
![frozen](https://user-images.githubusercontent.com/54820278/64141413-ec6ff880-cdd5-11e9-8c38-bf5c55886f6e.png)

**Comment by ripleymj** [comment]
We just added a fix that might help this. If it's still sitting there stuck, can you reboot, then try running it again? If it gets stuck again, we might need to meet up during TA hours to take a closer look at what's going wrong.

**Comment by Brennaser** [comment]
Ah, yes the golden rule of IT. Worked like a charm. Thank you, so much.

**Comment by ripleymj** [comment]
Glad to hear it! Thanks for working through this with me.
