### ISSUE TITLE
README manual steps do not work for Ubuntu 19.04

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#327]
Current manual steps only recommend `apt-get install ansible git`, but Ansible fails to launch on Ubuntu 19.04 because `/usr/bin/python` is missing. We should either recommend installing the `python` (2.7) package, or alternate steps that specify a working interpreter.

Also, Ansible immediately warns that `aptitude` is missing, and that it's falling back to `apt-get`, so we might want to recommend installing `aptitude` as well.

**Comment by kylelaker** [comment]
If Ubuntu has (wisely) made the decision to move away from including Python 2 by default, I'd rather not mess with that much. Can we look into just telling Ansible to use Python 3? https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html Seems it's been supported for a few versions now.

**Comment by kylelaker** [comment]
The warning about `aptitude` seems to have been removed in ansible/ansible#61782. Hopefully it will be gone by Ansible 2.9 or 2.10. It means that in the spring we'll have to deal with that warning being present, but hopefully by the fall we'll have a new enough version of Ansible to not have to deal with it.

Ubuntu seems to have moved away from `aptitude` and I don't think the `apt` module has any dependencies on it specifically.
