### ISSUE TITLE
Investigate bionic reference in Ubuntu apt sources

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#329]
`roles/common/templates/ubuntu.j2` specifies `bionic` on line 16. We should investigate if that should be templated to the current OS version, or needs to be pinned.

**Comment by kylelaker** [comment]
As the `git blame`-ee for this, I feel I should accept responsibility. This was added in 0a6b59c7/#176. I am pretty sure it should use `{{ ubuntu_release }}` like the other entries do. I believe hard-coding to `bionic` was an oversight.
