### ISSUE TITLE
jGRASP warns about unsupported Java distribution

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#339]
Somewhat similar to #154, we get a warning when starting jGRASP about unsupported Java; however, rather than being about the particular version, the warning is about the "vendor." In order to avoid the warning, we would need to either:

 - Install a "supported" install (Oracle, AdoptOpenJDK, etc.)
 - Use the jGRASP that bundles a JDK

Do we want to put in the effort to avoid this warning? If so I think just used the download with a bundled JDK would be easiest.

**Comment by ripleymj** [comment]
jGRASP has confirmed privately that they will consider this OpenJDK build for inclusion in their next release, and will be adding a "Don't show warning again".

**Comment by ripleymj** [comment]
jGRASP 2.0.6 beta 3 no longer warns about the Ubuntu JDK. Closing this in favor of #348 when it's released.
