### ISSUE TITLE
Update to Mint Tricia 19.3

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#347]
New base release expected within weeks. Beta test branch available here: https://github.com/ripleymj/cs-vm-build/tree/tricia-beta-test

**Comment by kylelaker** [comment]
Not sure if it's worth it, but the new System Reports lists 4 possible issues:
 - install hardware drivers
 - install language packs
 - install multimedia codecs
 - set the root password

These issues result in a exclamation triangle in the system bar. There is an "Ignore this problem" option for each one. We should consider ignoring at least the first two. We need to find a way to automate that.

**Comment by kylelaker** [comment]
The UUIDs of the reports to ignore get stored in the dconf key `/com/linuxmint/report/ignored-reports`, which is a list. The following will ignore all of the warnings.

```
dconf write /com/linuxmint/report/ignored-reports "['root-password-not-set', 'install-media-codecs', 'install-language-packs', 'drivers']"
```
| Warning | Report UUID |
|------------|-----------------|
| Driver    | `drivers` |
| Codec   | `install-media-codecs` |
| Langs    | `install-language-packs` |
| Pass      | `root-password-not-set` |

We've already got a task somewhere that's writing `dconf` settings, correct? Hopefully we can just extend that. We should only run this during OEM to avoid changing user settings.
