### ISSUE TITLE
Consider switching to flatpaks where possible

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#354]
At least two of the applications we ship are available on [Flathub](https://flathub.org/home): VS Code and Eclipse. As Mint now provides support for flatpaks through the software center (which pulls from Flathub by default), we should consider installing packages from there.

The [Ansible module](https://docs.ansible.com/ansible/latest/modules/flatpak_module.html) for flatpaks was not added until 2.6 and we're stuck on 2.5 in Mint 19.x; however, we should get a newer version with Mint 20. If we really want to use flatpaks, we could always use the `command` module in the interim.

**Comment by ripleymj** [comment]
I'd like to discourage anyone from taking this one on at this point. VS Code is only recommended as a deb or snap by Microsoft, and the flatpak doesn't appear to have much support from Microsoft. The existing apt setup is largely maintenance free for us.

Eclipse gives me a bad set of feelings. The flatpak does seem to be routinely maintained at this point, but using it would introduce a 3rd software distribution mechanism for us, would embed an additional JVM inside the flatpak, and would need a redesign of our (checkstyle, etc?) plugin installation. While I'm not a huge fan of manually updating the Eclipse download URL, it's on a predictable cadence and archived versions are maintained. We also have the ability to selectively target backports, though I don't think we've used that.

**Comment by kylelaker** [comment]
Since we haven't identified any actual places where this would be useful and we've been looking into it for about year, I am going to go ahead and call this officially "considered." It seems that in the best case, flatpaks would buy us nothing and in the worst case would increase maintenance burden and cause us to diverge from official documentation.
