### ISSUE TITLE
packer build broken with VirtualBox 6.1: VBoxManage: error: Unknown option: --clipboard

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#359]
It looks like the option has now become
`[--clipboard-mode disabled|hosttoguest|guesttohost|bidirectional]`.

Looks like we'll have to decide whether to build with 6.0 or 6.1 for Spring 2020.

**Comment by ripleymj** [comment]
Good catch. Looks like 6.1 just entered the Debian repo, so I'll add that to the beta test branch and start running a few trials to see if anything comes up with it.
