### ISSUE TITLE
RFC: Deprecate CS354 support

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#377]
Our CS354 robotics role has always been in an awkward place, since it was never formally requested, has no means of verification, has no known users, and is for a course only taught occasionally. For the fall image, I would like to remove the CS354 option from the setup GUI and stop testing it on a routine basis. I am not proposing to delete the role from the repository at this point, though I'd discourage anyone from spending significant time maintaining it. We can certainly bring it back later, though I think it would need to have a set of requirements defined, and a sponsor to test and validate correctness of the role.

**Comment by kylelaker** [comment]
I am in favor of this proposal; however, I'd advocate for a full removal of CS 354 from the repository. We've got git history if we want it to return; and over time the pieces of that role are going to slowly rot and stop working in even more ways if we stop testing. I'd rather they rot in the history than on HEAD. A well-named PR and commit message will make the removal easy to find and revert if that's every desired.

&lt;offtopic&gt;
I also like the concept of a sponsor and requirements being defined for all the courses but I think that's a larger conversation worthy of its own RFC. We do need someone to understand what IDEs 149 is using in a given semester and whether we're shipping a very old version of the 261 reference solution and utilities.

As far as knowing how many users a role has, I think that also comes back to the idea that's been floated of if/how we collect metrics. Perhaps reviving that conversation in earnest would be a worthwhile endeavor.
&lt;/offtopic&gt;
