### ISSUE TITLE
There is no default background on first boot for user

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#38]
As mentioned in comments on #34, something we are doing in the OEM script is breaking the background. The directory `/usr/share/backgrounds/linuxmint` is not present. That directory and the backgrounds within it are provided by `mint-artwork-gnome`, which does not seem to be a package we are removing.

**Comment by kylelaker** [comment]
Not 100% sure, but we're removing `libreoffice-*` which would include `libreoffice-style-mint`, which seems to be why `mint-artwork-gnome` gets pulled in in the first place.

Our options seem to be:

- explicitly install `mint-artwork-gnome`
- set a default background image some other way

**Comment by kylelaker** [comment]
Installing `mint-artwork-gnome` seems to correct the very "bare" `gksudo` prompt we had been seeing. @ripleymj if you're okay with just adding an `apt state=present name=mint-artwork-gnome`, I can go ahead and prep a PR.

**Comment by ripleymj** [comment]
Please do.
