### ISSUE TITLE
Update snaps during OEM

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#385]
Ubuntu 20.04 seems more reliant on default-installed snaps. We should update them during OEM so there's less to do at first boot. Usage in Mint is unknown at this point, but they should be updated too.

**Comment by kylelaker** [comment]
As of last summer, Mint didn't seem too impressed by snaps (https://blog.linuxmint.com/?p=3766) and as of the latest monthly blog post (https://blog.linuxmint.com/?p=3890#comment-155059), it seems like they don't intend to use snaps by default

**Comment by ripleymj** [comment]
If it's solely our Ubuntu test builds, then I'll probably ignore it. I'd like to keep this as a tracker so we can evaluate what might be necessary once we see a 20.04 LTS-powered Mint
