### ISSUE TITLE
Address Chromium "situation"

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#394]
Chromium as packaged is intentionally unusable in Mint 20. I'm working on another PR that removes it from the current playbook, so we don't give the wrong impression of it working. The alternatives are somewhat documented here: https://forums.linuxmint.com/viewtopic.php?f=42&t=321953 or we can close this with an intentional WONTFIX on record.

**Comment by kylelaker** [comment]
For additional history & context: Chromium support was added in #177 to support [Lab05](https://w3.cs.jmu.edu/cs101/unit05/Lab05-Networking.pdf) for CS 101. The Chrome/Chromium dev tools are used as part of the lab. For the features used, Firefox absolutely should be sufficient. Based on old emails from that time, it sounded like Chrome was never a _hard_ requirement, so Firefox might be a good option to pursue.

Of the alternatives, the "portable" option is probably the least bad. Snaps in Mint are asking for trouble, so is adding upstream `buster` sources; the beta or developer aren't ideal for distributing to potentially CS101 students who need to complete an assignment ASAP don't want to deal with beta bugs; ungoogled chromium requires adding another `apt` repo as well.

**Comment by ripleymj** [comment]
Mint has announced that they will be packaging Chromium directly: https://blog.linuxmint.com/?p=3969
