### ISSUE TITLE
Rename default git branch

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#395]
Current events have reignited the discussion of problematic terminology in software development, one of them being the git "master" branch. I'm under no delusion that this will save the world, but I think failing to take the smallest steps sends the wrong message about our awareness of the world around us. While I would prefer to wait to address this once GitHub finalizes its renaming plans, I think the sooner we do it this summer, the safer it will be, especially before we start distributing test images that rely on the default branch.

I'm proposing the following sequence of steps:

- Prepare a PR to address the items below
- Create "main" branch from "master" as that PR is merged. Update default branch to main
- Re-target any open PRs
- "master" branch remains intact for the duration of the summer for a safety measure, but ideally receives no further changes
- Build and distribute updated test images
- Create "ulyana" branch when fa20 image is ready, and delete "master"

A quick grep of the repository suggests the following things need to be changed:

- `meta/main.yml` in each role
- `uug_ansible_wrapper.py`
- `lint.yml`
- README/CONTRIBUTING (these need a larger review if someone wants to take that one)
- mint, ubuntu, and beta Packer files

**Comment by kylelaker** [comment]
FWIW, this has my complete support (and IMO the transition should absolutely be done for other repositories as well). Branch protection will also need to be updated on `cs-vm-build` unless the rules in place are more `*` than they were back when I had admin access.

An alternative set of steps would be to create `main` first, then open the PR against `main`. Which would leave `main` and `master` in a working state (though all new and existing changes should be targeted to `main`). `README.md` and `CONTRIBUTING.md` do absolutely need a rework; however, I wouldn't want to see that be a blocker for this change.

**Comment by ripleymj** [comment]
My intention is to address other repositories, but this is our most visible and potentially problematic....and this was a weird place to start a conversation about other repos.

Branch protection currently has two rules, one for `*` and one for `master` which I think is an artifact of having to remove accidental branches, but both provide equal protection.

I'm not dead set on a sequence for merge/branch, but I don't want to create `main` sooner than necessary and cause a diverge between the two.

**Comment by ripleymj** [comment]
This is now merged, and I'll be updating the default shortly. Please update your remotes accordingly.
