### ISSUE TITLE
Fix Python buffering in wrapper

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#404]
As pointed out during the review of #389, the output is really "laggy". This is new behavior on Mint 20/Ubuntu 20.04. It's the same with `spawn_sync` and `spawn_async`. We should try and clean that up so that it scrolls smoothly prior to shipping in the fall.

**Comment by tuckerzp** [comment]
@kylelaker Has this been looked into more since issue was opened?

**Comment by kylelaker** [comment]
@tuckerzp Nope! We're still seeing lots of buffering in the wrapper application and you'd see the same buffering if you ran the Ansible command directly. If you set `PYTHONUNBUFFERED=1` you can see that the output looks like you'd expect but polkit limits the environment variables that get retained in the child process. You'll have to dive into [this function](https://github.com/jmunixusers/cs-vm-build/blob/main/roles/common/templates/uug_ansible_wrapper.py#L382) and possibly toggle the way that the subprocess gets invoked in the call to `pkexec`. It's also possible we'll need to find a way to call/spawn `pkexec` through a more Python-friendly API. Or we may need to modify our [custom policy](https://github.com/jmunixusers/cs-vm-build/blob/main/roles/common/files/edu.jmu.uug.ansiblewrapper.policy).

**Comment by ripleymj** [comment]
@tuckerzp if this is something you want to work on, I just put a test VM image up that you can use https://w3.cs.jmu.edu/uug/testing/image-fa21.ova
