### ISSUE TITLE
New Eclipse version is available

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#425]
A new version of Eclipse IDE for Java Developers is available.

Version: 2020-12
URL: http://mirror.math.princeton.edu/pub/eclipse/technology/epp/downloads/release/2020-12/R/eclipse-java-2020-12-R-linux-gtk-x86_64.tar.gz
SHA1: 3a77893d865e25fb9e28f4b26efd59279ff79457

Does this need to go into `ulyana` or `main` sufficient?

**Comment by ripleymj** [comment]
Was just working on that for `main`. We haven't backported many Eclipses, especially since we had no users this fall.
