### ISSUE TITLE
Consider VirtualBox virtio storage

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#444]
Once this is merged and released, I'd like to test virtio for performance and compatibility: https://github.com/hashicorp/packer/pull/10632

**Comment by kylelaker** [comment]
Looks like this is live and can be used for [`nic_type`](https://www.packer.io/plugins/builders/virtualbox/iso#nic_type), [`hard_drive_interface`](https://www.packer.io/plugins/builders/virtualbox/iso#hard_drive_interface), and [`iso_interface`](https://www.packer.io/plugins/builders/virtualbox/iso#iso_interface); though if using EFI, `iso_interface` apparently must be set to `sata` (though the [section of the docs](https://www.packer.io/plugins/builders/virtualbox/iso#creating-an-efi-enabled-vm) that says that also uses an outdated means of setting EFI mode soo...).
