### ISSUE TITLE
Check .desktop file modes

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#49]
Aptana seems to get installed with 0644, but more recent files have been installing with 0755. What is necessary for .desktop files?

**Comment by ripleymj** [comment]
I feel like they shouldn't need execute, but then #22

**Comment by kylelaker** [comment]
Looks like if the file is in `/usr{/local,}/share/applications`, 0644 is an acceptable (or even preferred mode). If the file is not in one of those directories, then the mode must be 0755. `desktop-file-validate` does not report anything about permissions one way or the other.

**Comment by kylelaker** [comment]
References:

- https://unix.stackexchange.com/questions/373239/what-is-the-advantage-of-desktop-files-without-executable-bit-set#comment663823_373246
- https://lists.freedesktop.org/archives/xdg/2009-February/010209.html

**Comment by ripleymj** [comment]
So maybe removing `env xdg-open` in #47 shouldn't have happened, based on that freedesktop thread?

**Comment by kylelaker** [comment]
Yeah, so it seems like if the file is in `/usr{/local,}/share/applications`, then there is no executable flag and no shebang (since the file is not executable).

If the file is anywhere else, you need to mark the file is executable. Since shells do weird things if something is marked as executable but does have a shebang or ELF header, you need to add the shebang line. In Cinnamon (and hopefully most sane DEs) this will simply open the .desktop file in your web browser.

This does not seem to apply when Type=Link. Links are always allowed everywhere no matter what. Mode should not contain the executable bit and the file should not have a shebang.

**Comment by kylelaker** [comment]
Without being 0755, I think the files in the "trusted" directories can still have a shebang. It is just considered to be a comment.

**Comment by ripleymj** [comment]
Looking at the current output, we have this:

```
ls -l ~/Desktop
-rwxr-xr-x 1 ripleymj ripleymj 269 Dec  4 23:03 common.desktop
-rwxr-xr-x 1 ripleymj ripleymj 278 Dec  4 23:03 cs101.desktop
-rwxr-xr-x 1 ripleymj ripleymj 278 Dec  4 23:03 cs149.desktop
-rwxr-xr-x 1 ripleymj ripleymj 278 Dec  4 23:03 cs159.desktop
-rwxr-xr-x 1 ripleymj ripleymj 278 Dec  4 23:03 cs261.desktop
-rwxr-xr-x 1 ripleymj ripleymj 278 Dec  4 23:03 cs354.desktop
-rwxr-x--- 1 ripleymj ripleymj 311 Dec  4 23:05 stu-home.desktop
-rwxr-xr-x 1 ripleymj ripleymj 124 Dec  4 23:03 welcome-to-vm.desktop
```

Among these, nothing should have other permissions, and welcome can drop execute?

```
ls -l /usr/local/share/applications/
-rwxr-xr-x 1 root root 269 Dec  4 23:08 common.desktop
-rwxr-xr-x 1 root root 278 Dec  4 23:08 cs101.desktop
-rwxr-xr-x 1 root root 278 Dec  4 23:08 cs149.desktop
-rwxr-xr-x 1 root root 278 Dec  4 23:08 cs159.desktop
-rwxr-xr-x 1 root root 278 Dec  4 23:08 cs261.desktop
-rwxr-xr-x 1 root root 278 Dec  4 23:08 cs354.desktop
-rw-r--r-- 1 root root 179 Dec  4 23:08 eclipse.desktop
```

None of these should need execute?

**Comment by kylelaker** [comment]
Correct
