### ISSUE TITLE
uug-ansible-wrapping not waiting

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#50]
The end of the ansible wrapper script, where we wait for keyboard input, does not seem to fire when run from a desktop icon. Perhaps gksudo isn't running bash interactively, which would disable prompts.

**Comment by kylelaker** [comment]
--preserve-env or --login may help with this. It looks like there's a few other options like --description that might make the prompt more friendly as well.

**Comment by kylelaker** [comment]
We should look into just using [zenity](https://help.gnome.org/users/zenity/stable/). It seems to be in the OEM image, so I'll see if it works once the oem-config script runs. It displays a GTK dialog to the user. Not sure how I missed this before.

**Comment by ripleymj** [comment]
Assuming gksudo propagates the return value back, what if we moved gksudo from .desktop into the ansible-pull line? Then all of the zenitys could run unprivileged.

**Comment by kylelaker** [comment]
That's a much better idea. I'll play around to see if gksudo handles the return codes correctly.
