### ISSUE TITLE
Build Guest Additions for the right kernel

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#502]
One of the _first_ things we do within `scripts/oem-build` is setup Guest Additions. Unfortunately, that doesn't really work out so well. Because that builds some kernel modules and then we immediately upgrade the kernel. And then we ship the VM and from time-to-time, we see that users may not have Guest Additions entirely setup.

We should probably consider setting up Guest Additions within the VM _last_ (after Ansible) and using a command like `/sbin/rcvboxadd quicksetup all` to set up Guest Additions for all installed kernels.

Moving it after Ansible does cause the unfortunate issue that basically the last thing we do in the Ansible playbook is fill the disk with zeros to help with compression, so we'd be doing this _after_ that step.

If we were really passionate, we could handle the Guest Additions stuff during the `oem` role in Ansible too.

**Comment by ripleymj** [comment]
Are you seeing this problem? My impression has been that while the Additions are built for any kernel that's installed when they are installed. After that, its always seemed like `/etc/kernel/postinst.d/vboxadd` has kept them built for any new updates.

**Comment by kylelaker** [comment]
I thought I did? I built a Mint 21 VM and then had to manually install Guest Additions afterwards. But also maybe something else went wrong. I'll look into this more then.

**Comment by kylelaker** [comment]
Alright so I saw this on a fresh VM. I captured a `dmesg` and https://gist.github.com/kylelaker/082e3ca9fe2d70107acb73e1fa377a0d. It seems like doing some sort of significant resize of the VBox window works well enough to get the graphics to work. And the `vboxadd` service itself is happy. So I'm not entirely sure what's wrong.

**Comment by kylelaker** [comment]
Cannot reproduce on a modern build.
