### ISSUE TITLE
Revisit CS149 vs CS159

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#68]
Per @ChrisMayfield, `Eclipse` is used in CS149 and should be included there. Determine if we should still have separate roles so that `JGrasp` and `DrJava` are excluded from CS149. Also update README to reflect this.

**Comment by ChrisMayfield** [comment]
Many instructors use JGrasp/DrJava at the beginning and then switch to Eclipse at the end. Other instructors use one or the other, and others let students use whatever (not prescribed).

**Comment by ripleymj** [comment]
How did I manage to typo the one thing that mattered there? Does anybody recommend JGrasp or DrJava for 159?

**Comment by ChrisMayfield** [comment]
I'll ask, but I think generally people just use Eclipse or don't specify one at all.
