### ISSUE TITLE
Include Filezilla, possibly drop Home on Stu

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#69]
Per @ChrisMayfield, sftp via vfs is unnecessarily confusing for early students (101/149/159) and remote file access is better accomplished with FileZilla. Adding FileZilla is easy enough, bonus points if we pre-populate a connect entry in its configuration. Need to determine if we offend @lam2mo by dropping the sftp-vfs across the board in favor of sftp.

**Comment by lam2mo** [comment]
Not offended. :)

**Comment by kylelaker** [comment]
Should Filezilla be installed by a particular tag, a set of tags, or always?

**Comment by ripleymj** [comment]
Let's go with always for now.
