### ISSUE TITLE
Add local applications folder to OEM role

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#70]
If Cinnamon isn't detecting new apps because the /usr/local/applications folder isn't there on first boot, let's try adding it to the OEM role, and then populate it in later roles.

**Comment by kylelaker** [comment]
I had considered this previously and it wouldn't hurt to add a task for that; however, we do want to remember that not all users will necessarily be on a system that was set up with the OEM role.

**Comment by ripleymj** [comment]
Agreed, no intention to modify the common role as it exists now.
