### ISSUE TITLE
Choose and add a LICENSE

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#74]

**Comment by ripleymj** [comment]
I don't see a functional difference between BSD 2-clause, MIT, and ISC. All seem to require a line with name of the copyright holder, which is a bit blurry for us.

**Comment by kylelaker** [comment]
Having casually looked over a sample of Ansible Galaxy projects, MIT seems to be about the most common. BSD 2-clause and ISC are good licenses, but since functionally they're pretty similar, I do like the idea of choosing the one that is most common within a community if they all are good for us.

**Comment by lam2mo** [comment]
That seems reasonable to me. I have no preference.
