### ISSUE TITLE
Convert install script to Python

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/cs-vm-build#93]
Let's move discussion about this to its own issue, instead of burying it in a PR or comments on a gist: https://gist.github.com/kylelaker/8e8bc9f97514bcda6bfa813d7e7a6f72

**Comment by ripleymj** [comment]
For starters, a few ideas:

- The window resizes awkwardly and prefers to expand the checkboxes rather than the Ansible box
- The Run button should probably be disabled while a script is running
- It would be nice to have a status bar at the bottom, or somewhere, that indicates the URL and branch in effect
- A final PR should replace all the desktop and menu icons with this, and be sure to have a way to "refresh config" like now

**Comment by ripleymj** [comment]
Window resize seems to be better using `pack_start(var, False, True, 0)` rather than True, True for everything but the text box.

**Comment by kylelaker** [comment]
Thanks! I am about to submit a PR and I use False for the first boolean arg there. I believe all of the concerns above should be addressed in the initial PR, but I want to do a little more testing first
